server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://wpjiuekyortwor:33bc8a429bc61c03fc5a05cb24cfb1e3f9a8be54ea76d73cb6e0739480c884be@ec2-54-90-211-192.compute-1.amazonaws.com:5432/d82tespe3o73mm
    username: wpjiuekyortwor
    password: 33bc8a429bc61c03fc5a05cb24cfb1e3f9a8be54ea76d73cb6e0739480c884be
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
